### ISSUE TITLE
Komf won't build with latest nightly Rust

### ISSUE THREAD

**Issue by 26000** [koto-bank/komf#2]
![image](https://user-images.githubusercontent.com/23152347/26930603-6e085408-4c4d-11e7-8710-f764ab567ab9.png)
Was trying to install it to fix integration with IRChuu~ at last, but it doesn't want to work.

**Comment by vaartis** [comment]
Oh.. I'll look into it tommorow, probably

**Comment by 26000** [comment]
Thank you!

**Comment by vaartis** [comment]
Well, cant build rust on musl..

**Comment by alex-eg** [comment]
Fixed by #3
